<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>psl</string>
	</array>
	<key>name</key>
	<string>Parsel-Tongue</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.source.parsel</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.parsel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.parsel</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(deffun)\s+([a-zA-Z0-9_]+)\s*(\()</string>
			<key>name</key>
			<string>meta.function.source.parsel</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.parsel</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.source.parsel</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(defvar)\s+([a-zA-Z0-9_]+)\s*(\=)</string>
			<key>name</key>
			<string>meta.function.source.parsel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(for|if|then|else|lambda|while|in)\b</string>
			<key>name</key>
			<string>keyword.source.parsel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.source.parsel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(0|([1-9][0-9_]*))\b</string>
			<key>name</key>
			<string>constant.numeric.integer.source.parsel</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$\n</string>
			<key>name</key>
			<string>comment.line.documentation.source.rust</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.parsel</string>
	<key>uuid</key>
	<string>23e19ffa-2498-4a14-b44a-448315f56a60</string>
</dict>
</plist>
